// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using The25th_WEB.Data;

#nullable disable

namespace The25th_WEB.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260911143242_DisplayOrder")]
partial class _20260911143242_DisplayOrder
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("The25th_WEB.Models.Category", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Categories");

                b.HasData(
                    new
                    {
                        Id = 1,
                        DisplayOrder = 0,
                        Name = "Sci-Fi"
                    },
                    new
                    {
                        Id = 2,
                        DisplayOrder = 0,
                        Name = "Fantasy"
                    },
                    new
                    {
                        Id = 3,
                        DisplayOrder = 0,
                        Name = "Mystery"
                    });
            });
#pragma warning restore 612, 618
    }
}
